Controllers/UI/CatalogoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using LibraryPrimary2.Data;
using LibraryPrimary2.Models;
using Microsoft.AspNetCore.Identity;



namespace LibraryPrimary2.Controllers
{

    public class CatalogoController : Controller
    {
        private readonly ILogger<CatalogoController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly UserManager <IdentityUser> _userManager;
        private readonly SignInManager <IdentityUser> _signInManager;
        public CatalogoController(ILogger<CatalogoController> logger, 
        ApplicationDbContext context,
        UserManager <IdentityUser> userManager,
        SignInManager <IdentityUser> signInManager)
        {
            _logger = logger;
            _context= context;
            _userManager=userManager;
            _signInManager=signInManager;
        }

        public IActionResult Index()
        {
            var productos = from o in _context.DataProductos select o;
            return View(productos.ToList());
        }

        public async Task<IActionResult> Details(int? id){
            Producto? objProduct = await _context.DataProductos.FindAsync(id);
            if(objProduct==null){
                return NotFound();
            }
            return View(objProduct);
        }

        public async Task<IActionResult> Add(int? id){
            var userID = _userManager.GetUserName(User);
            if(userID==null){
                ViewData["Message"] = "Por favor debe loguearse antes de agregar un producto";
                List<Producto> productos = new List<Producto>();
                return  View("Index",productos);
            }else{
                var producto = await _context.DataProductos.FindAsync(id);
                Proforma proforma = new Proforma();
                proforma.Producto = producto;
                proforma.Precio = producto.Precio; //precio del producto en ese momento
                proforma.Cantidad = 1;
                proforma.UserID = userID;
                _context.Add(proforma);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/UI/ContactoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using LibraryPrimary2.Models;
using LibraryPrimary2.Data;

namespace LibraryPrimary2.Controllers
{
    public class ContactoController : Controller
    {
        private readonly ILogger<ContactoController> _logger;
        private readonly ApplicationDbContext _context;

        public ContactoController(ILogger<ContactoController> logger,ApplicationDbContext context)
        {
            _logger = logger;
             _context= context;
        }

        public IActionResult Index()
        {
            return View();
        }
        

        [HttpPost]
        public IActionResult Create(Contacto objContacto)
        {   
            _context.Add(objContacto);
            _context.SaveChanges();
            ViewData["Message"] = string.Concat("Estimado " , objContacto.Nombre, " te estaremos contactando pronto.");
            return View("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/UI/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using LibraryPrimary2.Data;
using LibraryPrimary2.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml.Table;
using OfficeOpenXml;
namespace LibraryPrimary2.Controllers
{
    public class PedidoController : Controller
    {
        private readonly ILogger<PedidoController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly UserManager <IdentityUser> _userManager;
        public PedidoController(ILogger<PedidoController> logger,
        ApplicationDbContext context,
        UserManager <IdentityUser> userManager)
        {
            _logger = logger;
            _context= context;
            _userManager=userManager;
        }

        public IActionResult ExportarExcel() 
        {
            string excelContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            var pedidos = _context.DataPedido.AsNoTracking().ToList();
            using (var libro = new ExcelPackage())
            {
                var worksheet = libro.Workbook.Worksheets.Add("Pedidos");
                worksheet.Cells["A1"].LoadFromCollection(pedidos, PrintHeaders: true);
                for (var col = 1; col < pedidos.Count + 1; col++)
                {
                    worksheet.Column(col).AutoFit();
                }
                // Agregar formato de tabla
                var tabla = worksheet.Tables.Add(new ExcelAddressBase(fromRow: 1, fromCol: 1, toRow: pedidos.Count + 1, toColumn: 2), "Pedidos");
                tabla.ShowHeader = true;
                tabla.TableStyle = TableStyles.Light6;
                tabla.ShowTotal = true;

                return File(libro.GetAsByteArray(), excelContentType, "Pedidos.xlsx");
            }
        }

        public IActionResult Index()
        {
            var pedidos = from o in _context.DataPedido select o;
            pedidos = pedidos.Where(s => s.Status.Contains("PENDIENTE"));            
            return View(pedidos.ToList());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/UI/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryPrimary2.Data;
using LibraryPrimary2.Models;
using LibraryPrimary2.Service;



namespace LibraryPrimary2.Controllers
{
    public class ProductoController : Controller
    {
        private readonly ProductoService _productoService;

        public ProductoController(ProductoService productoService)
        {
            _productoService = productoService;
        }

        // GET: Producto
        public async Task<IActionResult> Index()
        {
            var productos = await _productoService.GetAll();
            return productos != null ? 
                            View(productos) :
                            Problem("Entity set 'ApplicationDbContext.DataProductos'  is null.");
        }

        // GET: Producto/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _productoService.FirstOrDefault(id);
            if (producto == null)
            {
                return NotFound();
            }
            return View(producto);
        }

        // GET: Producto/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Producto/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Descripcion,Precio,PorcentajeDescuento,ImageName,Status")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                await _productoService.CreateOrUpdate(producto);
                return RedirectToAction(nameof(Index));
            }
            return View(producto);
        }

        // GET: Producto/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var producto = await _productoService.Get(id);
            if( producto == null){
                return NotFound();
            }
            return View(producto);
        }

        // POST: Producto/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Descripcion,Precio,PorcentajeDescuento,ImageName,Status")] Producto producto)
        {
            if (id != producto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _productoService.CreateOrUpdate(producto);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_productoService.ProductoExists(producto.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(producto);
        }

        // GET: Producto/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var producto = await _productoService.Get(id);
            if( producto == null){
                return NotFound();
            }
            return View(producto);
        }

        // POST: Producto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _productoService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryPrimary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryPrimary2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-yellow border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LibraryPrimary</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Pagina principal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Nosotros">¿Quienes somos?</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalogo" asp-action="Index">Catalogo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacto" asp-action="Index">Contactame</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <style>
    footer{
            background-color: rgb(243, 243, 207);
        }
        header{
            background-color: rgb(243, 243, 207);
        }
    </style>
    <footer >
          <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h4>Conócenos</h4>
                <p>Somos una empresa comprometida con...</p>
                <a href="https://www.facebook.com/profile.php?id=61551695705724">Facebook</a>
                <a href="https://instagram.com/primary.library?igshid=YTQwZjQ0NmI0OA==">Instagram</a>
            </div>
            <div class="col-md-6">
                <h4>Ubícanos</h4>
                <p>Estamos ubicados en:</p>
                <address>
                    Av. Abancay 689<br>
                    Lima<br>
                    Teléfono: (123) 456-7052
                </address>
                <section>

                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3901.862447329325!2d-77.03184848815143!3d-12.052983841969796!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9105c8b9c1994d9b%3A0xd6a4710b699c0283!2sAv.%20Abancay%20689%2C%20Lima%2015001!5e0!3m2!1ses-419!2spe!4v1695683196199!5m2!1ses-419!2spe" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </section>

            </div>
        </div>
    </div>          
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MenuAdminPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Collections.Generic;

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    IdentityUser identityUser  = await Task.Run(() => UserManager.GetUserAsync(User));
    var roles = await Task.Run(() => UserManager.GetRolesAsync(identityUser));

    @if(roles.Contains("Admin") ){
        <li class="nav-item">
            <a class="nav-link text-dark bi bi-cart" asp-area="" asp-controller="Pedido" asp-action="Index">Pedidos</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark bi bi-cart" asp-area="" asp-controller="Producto" asp-action="Index">Producto</a>
        </li>
    }
}