Controllers/UI/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using LibraryPrimary2.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System.Dynamic;
using LibraryPrimary2.Models;

namespace LibraryPrimary2.Controllers
{
    public class CarritoController : Controller
    {
        private readonly ILogger<CarritoController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly UserManager <IdentityUser> _userManager;
        public CarritoController(ILogger<CarritoController> logger,
        ApplicationDbContext context,
        UserManager <IdentityUser> userManager)
        {
            _logger = logger;
            _context= context;
            _userManager=userManager;
            
        }

        public IActionResult Index()
        {
            var userIDSession = _userManager.GetUserName(User);

            var items = from o in _context.DataCarrito select o;
            items = items.Include(p => p.Producto).
                Where(w => w.UserID.Equals(userIDSession) &&
                    w.Status.Equals("PENDIENTE")
                    );
            var itemsCarrito = items.ToList();
            var total = itemsCarrito.Sum(c => c.Cantidad * c.Precio);
            //MEMORIA
            dynamic model = new ExpandoObject();
            model.montoTotal = total;
            model.elementosCarrito = itemsCarrito;
            return View(model);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var itemproforma = await _context.DataCarrito.FindAsync(id);
            if (itemproforma == null)
            {
                return NotFound();
            }
            return View(itemproforma);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Save(int id, [Bind("Id,Cantidad,Precio,UserID")] Proforma itemcarrito)
        {
            if (id != itemcarrito.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(itemcarrito);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.DataCarrito.Any(e => e.Id == id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(itemcarrito);
        }


        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var itemcarrito = await _context.DataCarrito.FindAsync(id);
            _context.DataCarrito.Remove(itemcarrito);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/UI/PagoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using LibraryPrimary2.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using LibraryPrimary2.Models;

namespace LibraryPrimary2.Controllers
{
    public class PagoController : Controller
    {
         private readonly ILogger<PagoController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;        

        public PagoController(ILogger<PagoController> logger,
            ApplicationDbContext context,
            UserManager<IdentityUser> userManager )
        {
            _logger = logger;
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Create(Decimal monto)
        {

            Pago pago = new Pago();
            pago.UserID = _userManager.GetUserName(User);
            pago.MontoTotal = monto;
            return View(pago);
        }

        [HttpPost]
        public IActionResult Pagar(Pago pago)
        {
            pago.PaymentDate = DateTime.UtcNow;
            _context.Add(pago);

            var itemsProforma = from o in _context.DataCarrito select o;
            itemsProforma = itemsProforma.
                Include(p => p.Producto).
                Where(s => s.UserID.Equals(pago.UserID) && s.Status.Equals("PENDIENTE"));

            Pedido pedido = new Pedido();
            pedido.UserID = pago.UserID;
            pedido.Total = pago.MontoTotal;
            pedido.pago = pago;
            pedido.Status = "PENDIENTE";
            _context.Add(pedido);

            List<DetallePedido> itemsPedido = new List<DetallePedido>();
            foreach(var item in itemsProforma.ToList()){
                DetallePedido detallePedido = new DetallePedido();
                detallePedido.pedido=pedido;
                detallePedido.Precio = item.Precio;
                detallePedido.Producto = item.Producto;
                detallePedido.Cantidad = item.Cantidad;
                itemsPedido.Add(detallePedido);
            }


            _context.AddRange(itemsPedido);

            foreach (Proforma p in itemsProforma.ToList())
            {
                p.Status="PROCESADO"; //ATENDIDA
            }

            _context.UpdateRange(itemsProforma);

            _context.SaveChanges();

            ViewData["Message"] = "El pago se ha registrado y su pedido nro "+ pedido.ID +" esta en camino";
            return View("Create");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Carrito/Edit.cshtml
@model LibraryPrimary2.Models.Proforma

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Proforma</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Carrito" asp-action="Save">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="UserID" />
            <input type="hidden" asp-for="Precio" />
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Carrito/Index.cshtml
@model dynamic;
@using System.Collections.Generic;


@{
    ViewData["Title"] = "Carrito";
    IEnumerable<LibraryPrimary2.Models.Proforma> listItemsCarrito = new List<Proforma>();
    listItemsCarrito = @Model.elementosCarrito;
    Decimal montoTotal = @Model.montoTotal;
}

<h1>@ViewData["Title"]</h1>

<a class="btn btn-primary" asp-controller="Pago" 
        asp-action="Create" asp-route-monto="@montoTotal">Pagar</a><p>Total S/. @montoTotal</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => listItemsCarrito.FirstOrDefault().Producto.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => listItemsCarrito.FirstOrDefault().Cantidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => listItemsCarrito.FirstOrDefault().Precio)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (Proforma item in Model.elementosCarrito) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Producto.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>